### ISSUE TITLE
Quick fix for (at least) Sonoma on ARM

### ISSUE THREAD

**Issue by spdustin** [jtfedd/3d-radar#122]
```python
configVars = """
window-title Stormfront 3D Radar Viewer
icon-filename assets/icon/icon.ico
gl-version 3 2
"""

if __name__ == "__main__":
    loadPrcFileData("", configVars)

    base = ShowBase()
    app = App(base)
    base.run()
```

The `gl-version 3 2` was needed to get past shader error: `ERROR: shader/vertex.glsl:1: '' :  version '330' is not supported`

I just found this repo (good timing, because I'm in a nasty weather zone this evening!) and you're building something I've wanted to build for a long time. Are you looking for PRs?

**Comment by jtfedd** [comment]
@spdustin Unfortunately setting `gl-version 3 2` breaks a few other effects like clip planes and `LineSegs` thickness so I don't want to commit it to `main` just yet but I have a branch https://github.com/jtfedd/3d-radar/tree/mac-support which is fairly up-to-date (and could easily have main merged in) if you would like to use that for now!

**Comment by spdustin** [comment]
Awesome to see this merged, thanks!
